export const projectsList = [
  {
    title: 'kikx',
    desc: 'Lightweight web OS for running Python scripts',
    img: '/images/kikx-preview.jpg',
    tech: ['Python', 'Fastapi', 'JQuery', 'TailwindCSS'],
    repo: 'https://github.com/luvbyte/kikx',
  },
  {
    title: 'KittyChef',
    desc: 'Lightweight mobile toolkit for encoding, decoding, and transforming data',
    img: '/images/kittychef-preview.png',
    tech: ['Vue', 'TailwindCSS', 'JavaScript'],
    link: 'https://kittychef.netlify.app',
    repo: 'https://github.com/luvbyte/kittychef',
  },
  {
    title: 'zzz',
    desc: 'A lightweight framework for building interactive Python scripts',
    img: '/images/zzz-preview.jpg',
    tech: ['Python', 'Rich', 'Cmd2'],
    repo: 'https://github.com/luvbyte/zzz',
  },
  {
    title: 'Nebula',
    desc: 'A Python-powered web application that manages and runs automated bots',
    img: '/images/nebula-preview.jpg',
    tech: ['Python', 'FastAPI', 'vue', 'TailwindCSS'],
    repo: 'https://github.com/luvbyte/nebula',
  },
  {
    title: 'Teat',
    desc: 'This tool converts images into colorful ASCII-based text art',
    img: '/images/teat-preview.png',
    tech: ['Python', 'Pillow'],
    repo: 'https://github.com/luvbyte/teat',
  },
  //
  {
    title: 'SpaceText',
    desc: 'Texts in 3d space with emojis',
    img: '/images/space-text-preview.png',
    tech: ['HTML', 'JavaScript', 'ThreeJS'],
    link: 'https://space-text.netlify.app',
    repo: 'https://github.com/luvbyte/space-text',
  },
  {
    title: 'HeartMorph',
    desc: 'Heart Morph Using Particles :)',
    img: '/images/heart-morph-preview.png',
    tech: ['HTML', 'JavaScript', 'ThreeJS'],
    link: 'https://heart-morph.netlify.app',
    repo: 'https://github.com/luvbyte/heart-morph',
  },
  {
    title: 'LoveConfession',
    desc: 'A cute love confession page',
    img: '/images/love-confession-preview.png',
    tech: ['HTML', 'JavaScript', 'TailwindCSS'],
    link: 'https://f-love.netlify.app',
    repo: 'https://github.com/luvbyte/flirty-love-confession',
  },
  {
    title: 'BirthdayHeartGift',
    desc: 'Sukuna Giving Heart as Birthday Gift :)',
    img: '/images/bgh-preview.png',
    tech: ['HTML', 'JavaScript', 'TailwindCSS'],
    link: 'https://birthday-gift4u.netlify.app',
    repo: 'https://github.com/luvbyte/birthday-heart-gift',
  },
  {
    title: 'OSINT-Tools',
    desc: 'Useful Tools for open-source Intelligence',
    img: '/images/osint-tools-preview.png',
    tech: ['HTML', 'JavaScript', 'TailwindCSS'],
    link: 'https://osint-tools.netlify.app',
    repo: 'https://github.com/luvbyte/osint-tools',
  },
  {
    title: 'HinataCard',
    desc: 'A 3d website showcasing Hinata round cards with responsive design and clean UI',
    img: '/images/hinata-cards-preview.jpg',
    tech: ['HTML', 'JavaScript', 'ThreeJS'],
    link: 'https://hinata-cards.netlify.app/',
    repo: 'https://github.com/luvbyte/hinata-cards',
  },
  {
    title: 'EZQuiz',
    desc: 'Funny Quiz :)',
    img: '/images/ezquiz-preview.jpg',
    tech: ['HTML', 'JavaScript', 'TailwindCSS'],
    link: 'https://f-ezquiz.netlify.app',
    repo: 'https://github.com/luvbyte/ezquiz',
  },
  {
    title: 'Portfolio',
    desc: 'This webpage',
    img: '/images/portfolio-preview.jpg',
    tech: ['Vue', 'TailwindCSS'],
    repo: 'https://github.com/luvbyte/portfolio',
  },
  {
    title: 'Kchat',
    desc: 'A chat app build without database using python and vue',
    img: '/images/kchat-preview.png',
    tech: ['Python', 'FastAPI', 'vue', 'TailwindCSS'],
    repo: 'https://github.com/luvbyte/kchat',
  },
  {
    title: 'KawaiSpace',
    desc: 'A real-time Nuxt + Supabase platform for joining named private “islands” and chatting live',
    img: '/images/kawaispace-preview.png',
    tech: ['Supabase', 'Nuxt', 'Quasar'],
    repo: 'https://github.com/luvbyte/kawaispace',
  },
]
